# Glossário

- Raios do canhão e habilidades de agarro
    - Long Beam: Raio Longo
    - Charge Beam: Raio Carregado
    - Ice Beam: Raio de Gelo
    - Wave Beam: Raio Ondular
    - Wide Beam: Raio Amplo
    - Spazer Beam: Raio Esparso
    - Plasma Beam: Raio de Plasma
    - Power Grip: Garra de Força
    - Grapple Beam: Raio de Arpéu
    - Grapple Lasso: Laço de Arpéu
- Tipos de mísseis
    - Missile Launcher: Lança-mísseis
    - Missile: Míssil
    - Super Missile: Supermíssil (tudo junto)
    - Diffusion Missile: Míssil de Dispersão
- Tipos de bombas
    - Bomb: Bomba
    - Power Bomb: Bomba Energética
- Tipos de traje
    - Varia Suit: Traje Varia
    - Gravity Suit: Traje Gravitacional
    - Vi-O-La Suit: Traje Vi-O-La
    - Legacy Suit: Traje Legado
    - Fusion Suit: Traje Fusão
- Habilidades de esfera
    - Morph Ball: Morfosfera
    - Spider Ball: Aracnosfera
    - Spring Ball: Saltosfera
    - Speed Ball: Turbosfera
- Habilidades de perna e salto
    - Speed Booster: Acelerador
    - High Jump: Pulo Alto
    - Hi-Jump Boots: Botas de Pulo Alto
    - Screw Attack: Ataque Giratório
    - Space Jump: Salto Espacial
    - Power Slide: Superdeslize
- Morfologia
    - Alpha Metroid: Metroid Alfa
    - Zeta Metroid: Metroid Zeta
    - Gamma Metroid: Metroid Gama
    - Omega Metroid: Metroid Ômega
    - Crocomire: Crocomiro
    - Etecoons: Etequinos
    - Dachoras: Dácoras
- Localidades
    - Lower Brinstar: Brinstar Inferior
    - Wrecked Ship: Nave Danificada
    - Sector 1 (SRX): Setor 1 (SRX)
    - Sector 2 (TRO): Setor 2 (TRO)
    - Sector 3 (PYR): Setor 3 (PIR)
    - Sector 4 (AQA): Setor 4 (AQA)
    - Sector 5 (ARC): Setor 5 (ÁRT)
    - Sector 6 (NOC): Setor 6 (NOT)
- Diversos
    - Power Suit: Traje de Força
    - Missile Expansion: Expansão missilística
    - Arachno Impulse: Aracnoimpulso
    - Aeion: Éion
    - LogBook : Banco de Dados
    - Space Pirates : Piratas Espaciais
