name: Rules Validation

on:
  push:
    branches: ["**"]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Danger
        run: npm install -g danger

      - name: Run Danger Rules Check
        run: danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
